server:
  port: 8080

spring:
  application:
    name: gateway


management:
  endpoints:
    web:
      exposure:
        include: '*'



customer-reactive:
  uri: http://localhost:8081

order-socket:
  host: localhost
  port: 8181


logging:
  level:
    web: debug