server:
  port: 8080

spring:
  application:
    name: gateway


management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    export:
      wavefront:
        api-token: a79aca3e-fc83-4042-bffe-d78cb7f2f9b1
        uri: https://wavefront.surf

customer-reactive:
  uri: http://localhost:8081

order-socket:
  host: localhost
  port: 8181


logging:
  level:
    web: debug